version: "3.8"
services:
  controller:
    restart: always
    build: .
    container_name: localtunnel_server
    ports:
      - "12666:80"
    networks:
      localtunnel_network:
        ipv4_address: 172.66.82.12

  # nginx:
  #   container_name: localtunnel_nginx
  #   image: nginx:stable
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt # For production
  #     # - ./data/ssl:/etc/letsencrypt/live # For local
  #     - ./.deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./.deploy/nginx/conf.d:/etc/nginx/conf.d
  #   networks:
  #     localtunnel_network:
  #       ipv4_address: 172.66.82.88

networks:
  localtunnel_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.66.82.0/24
          ip_range: 172.66.82.0/24
          gateway: 172.66.82.1
